site_name: DataCap
site_url: https://databap.edurt.io/
site_author: devlive-community
site_description: >-
  DataCap is integrated software for data transformation, integration and visualization.
repo_name: devlive-community/datacap
repo_url: https://github.com/devlive-community/datacap
edit_uri: "https://github.com/devlive-community/datacap/blob/dev/docs/docs"

banners:
  - title: DataCap 2024.4.1 is released
    link: /release-latest.html
    description: <a href="https://github.com/devlive-community/datacap" class="text-white"> Do you ❤️ DataCap? Give us a 🌟 on GitHub </a>

copyright: Copyright &copy; 2023 devlive-community

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  include_search_page: true
  search_index_only: true
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/devlive-community
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/qianmoQ/
  status:
    new: Recently added
    1.10.0: 1.10.0
    1.11.0: 1.11.0
    1.14.0: 1.14.0
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/main.2f34a6de.min.css
  - assets/stylesheets/palette.ecc776e4.min.css
  - assets/stylesheets/datacap.css
extra_javascript:
  - assets/javascript/main.2dasf4fv.js
  - assets/javascript/datacap.js
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: devlive-community
      repo: datacap
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

use_directory_urls: false

plugins:
  - i18n:
      reconfigure_material: true
      default_language: en
      languages:
        - locale: zh
          name: Chinese (Simplified)
          build: true
          default: true
          nav_translations:
            NavHome: 首页
            NavDocumentation: 文档
            NavClient: 客户端
            NavManager: 管理
            NavSystem: 系统
            NavConnectors: 连接器
            NavFileSystem: 文件系统
            NavDeveloper: 开发
            NavDeveloperSpecification: 开发规范
            NavDeveloperPlugin: 插件
            NavDeveloperPluginKotlin: 插件 (Kotlin)
            NavReleaseNote: 更新日志
            NavDataset: 数据集
            NavDeploy: 安装部署
            NavWorkflow: 工作流
            ApiHome: 开放 API
            ApiUser: 用户 API
            ApiPlugin: 插件 API
            ApiDashboard: 仪表盘 API
            ApiMenu: 菜单 API
            ApiPipeline: 流水线 API
            ApiWorkflow: 工作流 API
            ApiMetadata: 元数据 API
            NavDriver: 驱动
        - locale: en
          name: English
          build: true
          default: false
          nav_translations:
            NavHome: Home
            NavDocumentation: Documentation
            NavClient: Clients
            NavManager: Manager
            NavSystem: System
            NavConnectors: Connectors
            NavFileSystem: File System
            NavDeveloper: Developer
            NavDeveloperSpecification: Specification
            NavDeveloperPlugin: Plugin
            NavDeveloperPluginKotlin: Plugin (Kotlin)
            NavReleaseNote: Release Note
            NavDataset: Dataset
            NavDeploy: Install Deploy
            NavWorkflow: Workflow
            ApiHome: Open API
            ApiUser: User API
            ApiPlugin: Plugin API
            ApiDashboard: Dashboard API
            ApiMenu: Menu API
            ApiPipeline: Pipeline API
            ApiWorkflow: Workflow API
            ApiMetadata: Metadata API
            NavDriver: Driver
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
  - git-authors
  - redirects:
      redirect_maps:
        release-latest.md: release/latest.md

nav:
  - NavHome:
    - index.md
  - NavDocumentation:
    - NavDeploy:
      - reference/getStarted/install.md
      - reference/getStarted/installContainers.md
      - reference/getStarted/installFromDockerCompose.md
      - reference/getStarted/installRainbond.md
    - reference/getStarted/query/home.md
    - reference/getStarted/dashboard/home.md
    - NavDataset:
      - reference/getStarted/dataset/create/home.md
      - reference/getStarted/dataset/adhoc/home.md
      - reference/getStarted/dataset/sync/home.md
      - reference/getStarted/dataset/history/home.md
      - reference/getStarted/dataset/clear/home.md
    - NavWorkflow:
      - reference/getStarted/workflow/create/home.md
      - reference/getStarted/workflow/error/home.md
      - reference/getStarted/workflow/stop/home.md
      - reference/getStarted/workflow/restart/home.md
      - reference/getStarted/workflow/logger/home.md
      - reference/getStarted/workflow/delete/home.md
      - reference/getStarted/workflow/dag/home.md
    - NavClient:
      - reference/clients/cli.md
    - NavManager:
        - reference/manager/profile/home.md
        - reference/manager/datasource/home.md
        - reference/manager/snippet/home.md
        - reference/manager/history/query/home.md
        - reference/manager/pipeline/home.md
        - reference/manager/report/home.md
    - NavSystem:
        - reference/system/functions/home.md
        - reference/system/sql/home.md
        - reference/system/menu/home.md
    - NavConnectors:
        - reference/connectors/influxdb/home.md
        - reference/connectors/solr/home.md
        - reference/connectors/timescale/home.md
        - reference/connectors/paradedb/home.md
        - reference/connectors/scylladb/home.md
        - reference/connectors/matrixone/home.md
        - reference/connectors/clickhouse/home.md
        - reference/connectors/mysql/home.md
        - reference/connectors/redis/home.md
        - reference/connectors/h2/home.md
        - reference/connectors/snowflake/home.md
        - reference/connectors/ydb/home.md
        - reference/connectors/zookeeper/home.md
        - reference/connectors/duckdb/home.md
        - reference/connectors/alioss/home.md
        - Apache Kafka:
            - reference/connectors/kafka/home.md
            - SHOW TOPICS: reference/sqlSyntax/connectors/kafka/show_topics.md
            - SHOW CONSUMERS: reference/sqlSyntax/connectors/kafka/show_consumers.md
            - SHOW DATABASES: reference/sqlSyntax/connectors/kafka/show_databases.md
            - SHOW TABLES: reference/sqlSyntax/connectors/kafka/show_tables.md
        - reference/connectors/ceresdb/home.md
        - reference/connectors/greptimedb/home.md
        - reference/connectors/questdb/home.md
        - reference/connectors/doris/home.md
        - reference/connectors/starrocks/home.md
        - reference/connectors/hologres/home.md
        - reference/connectors/hdfs/home.md
        - reference/connectors/pinot/home.md
        - reference/connectors/cassandra/home.md
    - NavFileSystem:
        - reference/filesystem/local/home.md
        - reference/filesystem/aliyun/home.md
        - reference/filesystem/qiniu/home.md
        - reference/filesystem/cos/home.md
        - reference/filesystem/s3/home.md
        - reference/filesystem/minio/home.md
  - NavReleaseNote:
      - 2024.4.1 (latest): release/latest.md
      - 2024.4.0: release/2024.4.0.md
      - 2024.3.11: release/2024.3.11.md
      - 2024.3.10: release/2024.3.10.md
      - 2024.03.9: release/2024.03.9.md
      - 2024.03.8: release/2024.03.8.md
      - 2024.03.7: release/2024.03.7.md
      - 2024.03.6: release/2024.03.6.md
      - 2024.03.5: release/2024.03.5.md
      - 2024.03.4: release/2024.03.4.md
      - 2024.03.3: release/2024.03.3.md
      - 2024.03.2: release/2024.03.2.md
      - 2024.03.1: release/2024.03.1.md
      - 2024.02.1: release/2024.02.1.md
      - 2024.01.1: release/2024.01.1.md
      - 1.18.0: release/1.18.0.md
      - 1.17.0: release/1.17.0.md
      - 1.16.0: release/1.16.0.md
      - 1.15.0: release/1.15.0.md
      - 1.14.0: release/1.14.0.md
      - 1.13.0: release/1.13.0.md
      - 1.12.0: release/1.12.0.md
      - 1.11.0: release/1.11.0.md
      - 1.10.0: release/1.10.0.md
      - 1.9.0: release/1.9.0.md
      - 1.8.0: release/1.8.0.md
      - 1.7.0: release/1.7.0.md
      - 1.6.0: release/1.6.0.md
      - 1.5.0: release/1.5.0.md
      - 1.4.0: release/1.4.0.md
      - 1.3.0: release/1.3.0.md
      - 1.2.0: release/1.2.0.md
      - 1.1.0.20221115: release/1.1.0.20221115.md
      - 1.0.0.20221015: release/1.0.0.20221015.md
  - NavDeveloper:
      - developer/specification/home.md
      - developer/server/home.md
      - developer/web/home.md
      - developer/doc/home.md
      - developer/sdk/home.md
      - developer/feature/home.md
      - NavDeveloperPlugin:
          - developer/plugin/java/home.md
      - NavDeveloperPluginKotlin:
          - developer/plugin/kotlin/home.md
          - developer/filesystem/home.md
          - developer/file/kotlin/home.md
          - developer/notify/kotlin/home.md
      - Other:
          - developer/pipeline/home.md
  - ApiHome:
      - api/common/response.md
      - api/common/page.md
      - ApiUser:
        - api/user/register.md
        - api/user/login.md
        - api/user/info.md
        - api/user/menu.md
        - api/user/list.md
      - ApiPlugin:
        - api/plugin/plugin.md
        - api/plugin/install.md
        - api/plugin/uninstall.md
      - ApiDashboard:
        - api/dashboard/list.md
        - api/dashboard/save.md
        - api/dashboard/edit.md
        - api/dashboard/get.md
        - api/dashboard/delete.md
      - ApiMenu:
        - api/menu/list.md
        - api/menu/save.md
        - api/menu/edit.md
      - ApiWorkflow:
        - api/workflow/list.md
        - api/workflow/save.md
        - api/workflow/edit.md
        - api/workflow/get.md
        - api/workflow/delete.md
        - api/workflow/log.md
        - api/workflow/restart.md
      - ApiMetadata:
          - api/metadata/database.md
          - api/metadata/databaseInfo.md
          - api/metadata/table.md
          - api/metadata/tableInfo.md
          - api/metadata/tableStatement.md
          - api/metadata/tableAutoIncrement.md
          - api/metadata/table-create.md
          - api/metadata/table-drop.md
          - api/metadata/table-truncate.md
          - api/metadata/engines.md
          - api/metadata/column.md
          - api/metadata/column-drop.md
          - api/metadata/column-change.md
          - api/metadata/data-types.md
  - NavDriver:
      - driver/mongodb.md
  - useCases.md
  - partners.md
